import numpy as np
import joblib
import xgboost as xgb

class TextClassifier:

    def __init__(self, model_path_lr: str, tokenizer_path_lr: str, model_path_xgb: str, tokenizer_path_xgb: str):
        # Load the models and vectorizers
        self.model_lr = joblib.load(model_path_lr)
        self.word2vec_model_lr = joblib.load(tokenizer_path_lr)
        self.model_xgb = joblib.load(model_path_xgb)
        self.word2vec_model_xgb = joblib.load(tokenizer_path_xgb)

    def _document_to_vector(self, doc: list, word2vec_model) -> np.array:
        vectors = [word2vec_model.wv[word] for word in doc if word in word2vec_model.wv.index_to_key]
        if vectors:
            return np.mean(vectors, axis=0)
        else:
            return np.zeros(word2vec_model.vector_size)

    def predict(self, text: str) -> dict:
        words = text.split()
        if len(words) > 30:
            vectorized_text = np.array([self._document_to_vector(words, self.word2vec_model_lr)])
            predicted_class = self.model_lr.predict(vectorized_text)[0]
            probability_gpt = self.model_lr.predict_proba(vectorized_text)[0][1]
        else:
            vectorized_text = np.array([self._document_to_vector(words, self.word2vec_model_xgb)])
            dtest = xgb.DMatrix(vectorized_text)
            probability_gpt = self.model_xgb.predict(dtest)[0] 
            predicted_class = 1 if probability_gpt >= 0.5 else 0

        probability_human = 1 - probability_gpt
        probability_human_percentage = probability_human * 100
        probability_gpt_percentage = probability_gpt * 100

        prediction_statement = (f"The text has a {probability_human_percentage:.2f}% chance of being written by a 'human' "
                                f"and a {probability_gpt_percentage:.2f}% chance of being generated by 'gpt'.")
        if probability_gpt > 0.6:
            opinion = "The text is most likely generated by 'gpt'."
        elif probability_human > 0.6:
            opinion = "The text is most likely written by a 'human'."
        else:
            opinion = "The text has a balanced probability between 'human' and 'gpt', making it challenging to decisively classify."

        return {
            'predicted_class': 'human' if predicted_class == 0 else 'gpt',
            'statement': prediction_statement,
            'opinion': opinion
        }